language: android
android:
        components:
                - tools
                - platform-tools
                - tools
                - build-tools-25.0.2
                - android-25
                - extra-android-m2repository
                - extra-google-m2repository
               
before_script: - chmod +x gradlew
script: ./gradlew testDevelopmentDebug
