language: android
before_install:
- chmod +x gradlew
android:
        components:
                - tools
                - platform-tools
                - tools
                - build-tools-25.0.2
                - android-25
                - extra-android-m2repository
                - extra-google-m2repository
                - extra-google-google_play_services
                - addon-google_apis-google-19
                - extra-android-support

        licenses:
                - 'android-sdk-preview-license-52d11cd2'
                - 'android-sdk-license-.+'
                - 'google-gdk-license-.+'
                

script:
    - ./gradlew build check coveralls
                  
